const personajes = [
    "Harry Potter", "Hermione Granger", "Ron Weasley", "Hagrid", "Dumbledore", "Voldemort",
    "Batman", "Superman", "Flash", "Wonder Woman", "Aquaman", "Cyborg", "Joker", "Harley Quinn",
    "Spider-Man", "Iron Man", "Captain America", "Hulk", "Thor", "Black Widow", "Hawkeye",
    "Doctor Strange", "Black Panther", "Star-Lord", "Gamora", "Drax", "Rocket", "Groot",
    "Loki", "Wanda Maximoff", "Vision", "Thanos",
    "Goku", "Vegeta", "Gohan", "Trunks", "Piccolo", "Majin Buu", "Freezer",
    "Naruto", "Sasuke", "Sakura", "Kakashi", "Itachi", "Jiraiya", "Madara", "Obito",
    "Luffy", "Zoro", "Sanji", "Nami", "Usopp", "Chopper", "Robin", "Franky", "Brook", "Jinbe",
    "Tanjiro", "Nezuko", "Zenitsu", "Inosuke", "Rengoku",
    "Aang", "Zuko", "Katara", "Toph", "Sokka",
    "Homer Simpson", "Bart Simpson", "Lisa Simpson", "Marge Simpson",
    "Peter Griffin", "Stewie Griffin", "Brian Griffin",
    "Scooby Doo", "Shaggy", "Fred", "Velma", "Daphne",
    "Mario", "Luigi", "Yoshi", "Peach", "Bowser", "Toad", "Wario", "Waluigi",
    "Link", "Zelda", "Ganondorf",
    "Sonic", "Tails", "Knuckles", "Shadow",
    "Freddy Fazbear", "Bonnie", "Chica", "Foxy", "Springtrap",
    "Steve (Minecraft)", "Alex (Minecraft)", "Creeper", "Enderman", "Zombie",
    "Kratos", "Atreus",
    "Geralt de Rivia", "Yennefer", "Ciri",
    "Master Chief", "Cortana",
    "Lara Croft", 
    "Pac-Man", 
    "Ash Ketchum", "Pikachu", "Charizard", "Bulbasaur", "Squirtle", "Mewtwo",
    "Messi", "Cristiano Ronaldo", "Neymar", "Mbappé", "Haaland", "Lewandowski", "Vinicius Jr",
    "Pedri", "Gavi", "Lamine Yamal", "João Félix", "Ter Stegen", "Lewandowski",
    "Kimmich", "Musiala", "Kane", "Modric", "Bellingham", "Salah", "Suárez",
    "Canelo Álvarez", "Conor McGregor",
    "Bad Bunny", "Karol G", "Feid", "J Balvin", "Maluma", "Shakira", "Rauw Alejandro",
    "Duki", "Peso Pluma", "Natanael Cano", "Anuel", "Arcángel",
    "Ariana Grande", "Taylor Swift", "Billie Eilish", "The Weeknd", "Drake", "Doja Cat",
    "Travis Scott", "Kanye West",
    "Santa Claus", "Duende", "Reno", "Grinch",
    "Bob Esponja", "Patricio", "Calamardo", "Don Cangrejo", "Arenita", "Plankton",
    "Shrek", "Burro", "Fiona", "Gato con Botas",
    "Jack Sparrow",
    "John Wick",
    "James Bond",
    "Rambo",
    "Terminator",
    "Rocky Balboa",
    "Michael Jordan", "LeBron James", "Stephen Curry",
    "Elon Musk", "Jeff Bezos", "Mark Zuckerberg",
    "MrBeast", "AuronPlay", "Ibai", "TheGrefg", "ElRubius",
    "Optimus Prime", "Bumblebee",
    "Chucky", "Annabelle", "Pennywise",
    "Wednesday Addams", "Morticia Addams",
    "Barbie", "Ken",
    "Bluey", "Bingo",
    "Peppa Pig", "George Pig",
    "Hércules", "Zeus", "Poseidón", "Hades",
    "Thor (nórdico)", "Odín", "Loki (nórdico)",
    "Cleopatra", "Napoleón", "Albert Einstein",
    "Sherlock Holmes", "Dr. Watson",
    "Willy Wonka", 
    "Waldo",
    "Chespirito", "El Chavo", "Quico", "La Chilindrina", "Don Ramón", "Doña Florinda",
    "Goku Ultra Instinct", "Naruto Modo Sabio", "Luffy Gear 5",
    "Miles Morales", "Peter Parker", "Spider-Gwen",
    "Hulkbuster",
    "Ant-Man", "Wasp",
    "Shang-Chi",
    "Moon Knight",
    "Daredevil",
    "Punisher",
    "Ghost Rider",
    "Mandalorian", "Grogu (Baby Yoda)",
    "Darth Vader", "Luke Skywalker", "Yoda", "R2-D2", "C-3PO", "Han Solo", "Leia",
    "Rick", "Morty",
    "Finn", "Jake (Adventure Time)",
    "Ben 10", "Kevin", "Gwen",
    "Gumball", "Darwin",
    "Ratatouille", "Remy", "Alfredo",
    "Sully", "Mike Wazowski",
    "Dash", "Violet", "Mr. Increíble", "Elastigirl",
    "Wall-E", "EVA",
    "Hipo", "Chimuelo",
    "Marty", "Alex", "Gloria", "Melman",
    "BMO", "Ice King",
    "Ken Block",
    "Spider-Man 2099",
    "Hancock",
    "Hércules (Disney)",
    "Buzz Lightyear", "Woody", "Jessie",
    "Mickey", "Minnie", "Donald", "Goofy",
    "Pumba", "Timon", "Simba", "Mufasa", "Scar",
    "Olaf", "Elsa", "Anna", "Kristoff"
];
